### ISSUE TITLE
[Bug]: SQRuff Github Action - 404 Error

### ISSUE THREAD

**Issue by davebelais** [quarylabs/sqruff#1369]
### What happened?

When using `quarylabs/install-sqruff-cli-action@main` in a workflow, using an `ubuntu-latest` runner, I get a 404 error when it tries to download from `https://github.com/quarylabs/sqruff/releases/download/v0.25.9/sqruff-linux-x86_64-musl.tar.gz`, which appears to be missing... The following workflow replicates the issue:

```
name: test
on:
  push:
    branches:
    - '*'
jobs:
  lint-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarylabs/install-sqruff-cli-action@main
```

### Version

I am using `quarylabs/install-sqruff-cli-action@main`, which currently tries to pull `v0.25.9`.

### Checked in Playground

- [ ] I have checked this bug in the [playground](https://playground.quary.dev/?secondary=Format).

**Comment by davebelais** [comment]
...when I change the workflow to the following, it works—so it looks like recent releases simply don't include all the needed assets:

```yaml
name: test
on:
  push:
    branches:
    - '*'
jobs:
  lint-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          version: v0.25.5
      - uses: quarylabs/install-sqruff-cli-action@main
```
