### ISSUE TITLE
[Bug]: Unable to properly format templated SQL code

### ISSUE THREAD

**Issue by seanhagen** [quarylabs/sqruff#1478]
### What happened?

I'm trying to get `sqruff` set up to format SQL code that's used within Apache Airflow.  The code is called from Airflow using the `SnowflakeOperator`, and the calling code looks a little bit like this:

```python
default_parameters = {
    "environment_type": Variables.get('env'),
}

# then later:
model = SnowflakeOperator(
     task_id='model',
     snowflake_conn_id='snowflake_default',
     sql='model/3_process.sql',
     parameters=default_parameters,
     dag=dag
)
```

Then in the SQL file, the parameters are used like this:

```sql
use role ownership_role;

set schema = %(environment_type)s;
use schema identifier($schema)

-- file continues with more queries after this point
```

When trying to format with `sqruff`, this gets changed to the following:

```sql
use role ownership_role;

set schema = % (environment_type) s ;
use schema identifier (
$schema);
```

Additionally, everything else in the file doesn't get formatted properly. For example, this is some SQL from later in the file:
```sql
create or replace table refunds_aggregate_model as (
select
ft.transaction_date,
ft.trip_id,
```

If I comment out the lines causing issues, that gets formatted properly:
```sql
create or replace table refunds_aggregate_model as (
  select
    ft.transaction_date,
    ft.trip_id,
```

I'm configuring `sqruff` via a `.sqruff` file, and here's the content of that file:
```toml
[sqruff]
dialect = snowflake
rules = all
max_line_length = 120
ignore = raw

[sqruff:indentation]
indent_unit = space
tab_space_size = 2
indented_joins = true
indented_ctes = true
indented_using_on = true

[sqruff:templater:jinja]
apply_dbt_builtins = true

[sqruff:templater:jinja.context]
environment_type = prod

[sqruff:layout:type.alias_expression]
spacing_before = align
align_within = select_clause
align_scope = bracketed

[sqruff:layout:type.comma]
# Allowing trailing spaces after commas
spacing_before = touch
# Allowing commas to be set at end-of-line
line_position = trailing

[sqruff:rules:aliasing.table]
# Forcing aliasing using AS on tables
aliasing = explicit

[sqruff:rules:aliasing.column]
# Forcing aliasing using AS on columns
aliasing = explicit

# Forcing all keywords / functions and other items
# to be written lowercase
[sqlruff:rules]
capitalisation_policy = lower
extended_capitalisation_policy = lower
[sqruff:rules:capitalisation.keywords]
capitalisation_policy = lower
extended_capitalisation_policy = lower
[sqruff:rules:capitalisation.identifiers]
capitalisation_policy = lower
extended_capitalisation_policy = lower
[sqruff:rules:capitalisation.functions]
capitalisation_policy = lower
extended_capitalisation_policy = lower
[sqruff:rules:capitalisation.literals]
capitalisation_policy = lower
extended_capitalisation_policy = lower
[sqruff:rules:capitalisation.types]
capitalisation_policy = lower
extended_capitalisation_policy = lower

[sqruff:rules:convention.terminator]
multiline_newline = false

[sqruff:layout:type.casting_operator]
spacing_before = touch
spacing_after = touch:inline

[sqruff:rules:layout.set_operators]
# Return to line when having a UNION or UNION ALL
set_operator_on_new_line = ['UNION', 'UNION ALL']

[sqruff:layout:type.start_square_bracket]
# The first character after a bracket should stick to the bracket
spacing_after = touch

[sqruff:layout:type.end_square_bracket]
# The last character before the end of bracket should stick to the bracket
spacing_before = touch

[sqruff:layout:type.common_table_expression]
# Make a query within a CTE fit in 1 line when possible
spacing_within = single:inline

[sqruff:rules:convention.casting_style]
# Cast all convert&cast to ::
preferred_type_casting_style = shorthand

[sqruff:layout:type.having_clause]
line_position = alone

[sqruff:layout:type.limit_clause]
line_position = alone
```

I've also tried using this instead:
```sql
set schema = {{ environment_type }};
```

But that gets formatted to this:
```sql
set schema = { { environment_type } };
```

And the rest of the SQL still doesn't get formatted properly.

Is there a configuration option for fixing this so that the SQL code gets formatted properly?

### Version

0.25.24

### Checked in Playground

- [x] I have checked this bug in the [playground](https://playground.quary.dev/?secondary=Format).
