### ISSUE TITLE
[Bug]: Sqruff keeps wanting to add invalid spaces

### ISSUE THREAD

**Issue by seanhagen** [quarylabs/sqruff#1480]
### What happened?

Sqruff keeps trying to apply LT01 where it shouldn't:
 - between a function name and the first '('
 - between the '!' and '=' of a not-equal comparison operator

For example, it keeps trying to change this line from a query:
```sql
WHEN charIndex('.', to_char(PAYMENT_RECORD_ID)) != 0 THEN '73'
```

To this:
```sql
WHEN charIndex ('.', to_char (PAYMENT_RECORD_ID)) ! = 0 THEN '73'
```

I tried seeing if I could change the not-equal operator to `<>`, but Sqruff would also try to change that to `< >` instead.

Here's my config:
```toml
[sqruff]
dialect = snowflake
rules = all
max_line_length = 130
ignore = templating
#exclude_rules = AM04,RF02,CV11

[sqruff:indentation]
indent_unit = space
tab_space_size = 2
indented_joins = true
indented_ctes = true
indented_using_on = true

[sqruff:templater:jinja]
apply_dbt_builtins = true

[sqruff:templater:jinja.context]
environment_type = prod

#######################################
# Rules                               #
#######################################
[sqlruff:rules]
# Forcing all keywords / functions and other items
# to be written lowercase
capitalisation_policy = lower
extended_capitalisation_policy = lower

[sqruff:rules:layout.spacing]


[sqruff:rules:aliasing.table]
# Forcing aliasing using AS on tables
aliasing = explicit

[sqruff:rules:aliasing.column]
# Forcing aliasing using AS on columns
aliasing = explicit

# Forcing all keywords / functions and other items
# to be written lowercase
[sqruff:rules:capitalisation.keywords]
capitalisation_policy = lower
extended_capitalisation_policy = lower
[sqruff:rules:capitalisation.identifiers]
capitalisation_policy = lower
extended_capitalisation_policy = lower
[sqruff:rules:capitalisation.functions]
capitalisation_policy = lower
extended_capitalisation_policy = lower
[sqruff:rules:capitalisation.literals]
capitalisation_policy = lower
extended_capitalisation_policy = lower
[sqruff:rules:capitalisation.types]
capitalisation_policy = lower
extended_capitalisation_policy = lower

# Force semi-colon to be on same line as last part of query
[sqruff:rules:convention.terminator]
multiline_newline = false

# Force using '!=' instead of '<>'
[sqruff:rules:convention.not_equal]
preferred_not_equal_style = c_style

[sqruff:rules:layout.set_operators]
# Return to line when having a UNION or UNION ALL
set_operator_on_new_line = ["UNION", "UNION ALL"]

[sqruff:rules:convention.casting_style]
# Cast all convert&cast to ::
preferred_type_casting_style = shorthand

#######################################
# Layout                              #
#######################################
[sqruff:layout:type.alias_expression]
spacing_before = align
align_within = select_clause
align_scope = bracketed

[sqruff:layout:type:function_name]
spacing_within = touch
spacing_after = touch

[sqruff:layout:type.comma]
# Allowing trailing spaces after commas
spacing_before = touch
# Allowing commas to be set at end-of-line
line_position = trailing

[sqruff:layout:type:binary_operator]
spacing_within = touch
line_position = leading

[sqruff:layout:type.comparison_operator]
spacing_within = touch
line_position = leading

[sqruff:layout:type.casting_operator]
spacing_before = touch
spacing_after = touch:inline

[sqruff:layout:type:start_angle_bracket]
spacing_after = touch

[sqruff:layout:type:end_angle_bracket]
spacing_before = touch

[sqruff:layout:type.start_square_bracket]
# The first character after a bracket should stick to the bracket
spacing_after = touch

[sqruff:layout:type.end_square_bracket]
# The last character before the end of bracket should stick to the bracket
spacing_before = touch

[sqruff:layout:type.common_table_expression]
# Make a query within a CTE fit in 1 line when possible
spacing_within = single:inline

[sqruff:layout:type.having_clause]
line_position = alone

[sqruff:layout:type.limit_clause]
line_position = alone
```

### Checked in Playground

- [x] I have checked this bug in the [playground](https://playground.quary.dev/?secondary=Format).
