### ISSUE TITLE
T-SQL dialect creates double nesting for select_clause_modifier and from_expression_element

### ISSUE THREAD

**Issue by Fank** [quarylabs/sqruff#1672]
## Description

The T-SQL dialect implementation creates unexpected double nesting in the AST for `select_clause_modifier` and `from_expression_element` nodes. This results in redundant wrapper nodes that don't appear in other dialects like ANSI.

## Current Behavior

When parsing T-SQL queries, the AST shows double nesting:

```yaml
# In select_top.yml
select_clause_modifier:
  - select_clause_modifier:  # <-- duplicate nesting
    - keyword: TOP
    - numeric_literal: '10'

# And also:
from_expression_element:
  - from_expression_element:  # <-- duplicate nesting
    - table_expression:
      - table_reference:
        - object_reference:
          - naked_identifier: customers
```

## Expected Behavior

Based on ANSI dialect behavior, there should only be one level of nesting:

```yaml
# Expected (like in ANSI)
from_expression_element:
  - table_expression:
    - table_reference:
      - naked_identifier: customers
```

## Root Cause

The issue is in the T-SQL dialect implementation (`crates/lib-dialects/src/tsql.rs`):

1. For `SelectClauseModifierSegment` (lines 263-292):
```rust
dialect.replace_grammar(
    "SelectClauseModifierSegment",
    NodeMatcher::new(
        SyntaxKind::SelectClauseModifier,  // This creates a wrapper
        // ... content ...
    )
    .to_matchable(),
);
```

2. For `FromExpressionElementSegment` (lines 828-848):
```rust
dialect.replace_grammar(
    "FromExpressionElementSegment", 
    NodeMatcher::new(
        SyntaxKind::FromExpressionElement,  // This creates a wrapper
        // ... content ...
    )
    .to_matchable(),
);
```

The problem is that `NodeMatcher::new` with a `SyntaxKind` creates a wrapper node, but the segment itself (e.g., `SelectClauseModifierSegment`) already represents that node type. This results in double nesting.

## Affected Files

- `crates/lib-dialects/src/tsql.rs` - The dialect implementation
- Test files showing the double nesting:
  - `test/fixtures/dialects/tsql/select_top.yml`
  - `test/fixtures/dialects/tsql/select_top_percent.yml`
  - `test/fixtures/dialects/tsql/al02_implicit_column_alias.yml`

## Proposed Solution

The grammar replacements should be restructured to avoid the double wrapping. This might involve:
1. Not using `NodeMatcher` for these specific replacements
2. Using a different approach that doesn't create the redundant wrapper
3. Or adjusting how segments are defined to work with the current pattern

## Additional Context

This issue was discovered while working on T-SQL dialect support in PR #1664. The double nesting doesn't break functionality but creates an inconsistent AST structure compared to other dialects.
