### ISSUE TITLE
LT01: T-SQL split comparison operator joining requires reflow system enhancement

### ISSUE THREAD

**Issue by Fank** [quarylabs/sqruff#1707]
## Problem

T-SQL allows split comparison operators like `> =` which should be joined to `>=` by the LT01 spacing rule, but the current reflow system cannot handle this scenario.

## Current Behavior

```sql
-- Input
SELECT col1 FROM table1 WHERE 1 > = 1

-- Expected Output  
SELECT col1 FROM table1 WHERE 1 >= 1

-- Actual Output
SELECT col1 FROM table1 WHERE 1 > = 1  -- No change
```

## Root Cause

1. **T-SQL dialect correctly defines** compound operators like `>=` as single tokens in the lexer
2. **When source has split operators** like `> =`, they get tokenized as separate `>` and `=` tokens
3. **Reflow system lacks logic** to join separate tokens back into compound operators
4. **Configuration exists** (`comparison_operator.spacing_within = touch`) but isn't applied to split tokens

## Technical Details

- **Failing tests**: `test_comparison_operator_fix`, `test_fix_tsql_spaced_chars` in LT01
- **Location**: `/crates/lib/src/utils/reflow/` system
- **Config**: `[sqlfluff:layout:type:comparison_operator] spacing_within = touch` should apply

## Proposed Solution

Enhance the reflow system to:
1. Detect when separate tokens should form compound operators
2. Apply `spacing_within = touch` rules to join them  
3. Handle T-SQL-specific multi-character operators: `>=`, `<=`, `!=`, `<>`, `!>`, `!<`

## Impact

- **Priority**: Medium - affects T-SQL code formatting quality
- **Scope**: Requires reflow system architectural changes
- **Related operators**: All T-SQL compound comparison and assignment operators

## Labels
- `enhancement`
- `dialect:tsql` 
- `rule:LT01`
- `reflow-system`

**Comment by Fank** [comment]
After investigating this issue and attempting a fix in PR #1747, we've discovered that the root cause is different than initially described.

## Key Findings:

1. **Parser Issue, Not Reflow**: The parser is marking `> =` as `unparsable`, which means it doesn't recognize it as a valid comparison operator. This happens before the reflow system is even involved.

2. **Questionable Syntax Validity**: We couldn't find any Microsoft SQL Server documentation that confirms `> =` (with space) is valid T-SQL syntax. All official examples show comparison operators as single tokens: `>=`, `<=`, `!=`, `<>`.

3. **Test Parse Tree** shows the problem clearly:
   ```yaml
   - where_clause:
       - keyword: WHERE
       - expression:
           - column_reference:
               - naked_identifier: a
   - whitespace: ' '
   - unparsable:      # <-- The parser fails here
       - raw_comparison_operator: '>'
       - whitespace: ' '
       - raw_comparison_operator: =
   ```

## Recommendation:

We need to verify whether SQL Server actually accepts `SELECT 1 WHERE 1 > = 2` as valid syntax:
- If it's **NOT valid** (most likely): The issue and tests are based on incorrect assumptions
- If it **IS valid**: The fix needs to be in the T-SQL parser/dialect definition, not the reflow system

Without confirmation that this is valid T-SQL syntax, we shouldn't proceed with any fix.
