### ISSUE TITLE
sqruff.toml support

### ISSUE THREAD

**Issue by musjj** [quarylabs/sqruff#798]
TOML config support would be nice to have, especially in a Rust project.

**Comment by benfdking** [comment]
Hey @musjj,

Thanks for the issue; I'm just trying to understand your request exactly. You can already configure sqruff with a a `.sqruff` file? Is there any particular difference you mean?

**Comment by musjj** [comment]
`.sqruff` currently uses the `ini` format (particularly, sqlfluff's special flavor of it).

```ini
[sqlfluff]
templater = jinja

[sqlfluff:indentation]
indented_joins = False
```

It would be nice if we can just use `toml`, which is probably more familiar to Rust users:

```toml
[sqlfluff]
templater = "jinja"

[sqlfluff.indentation]
indented_joins = false
```
