### ISSUE TITLE
unexpected `layout.spacing` rule application on `grant` statements

### ISSUE THREAD

**Issue by demhadais** [quarylabs/sqruff#924]
I wouldn't necessarily classify this as a bug, but it seems unexpected to me that the following line of SQL:
```sql
grant some_role to a_user;
```
triggers the [`layout.spacing`](https://github.com/quarylabs/sqruff/blob/main/docs/rules.md#layoutspacing) rule, causing `sqruff` to reformat to:
```sql
grant some_role to a_user ; -- there is now a space between 'a_user' and ';'
```

Is this behavior desired/expected? For reference, I'm running `sqruff` v0.20.2, and my `.sqruff` file is just
```
[.sqruff]
dialect = postgres
```

**Comment by gvozdvmozgu** [comment]
Strange, I can't reproduce that behavior in the playground.

**Comment by gvozdvmozgu** [comment]
```powershell
PS C:\Users\gvozdvmozgu\Projects\sqruff> cat .\.sqlfluff
[.sqruff]
dialect = postgres
PS C:\Users\gvozdvmozgu\Projects\sqruff> cat .\pg.sql   
grant some_role to a_user;
PS C:\Users\gvozdvmozgu\Projects\sqruff> cargo r --quiet -- lint .\pg.sql
The linter processed 1 file(s).
All Finished 📜 🎉
PS C:\Users\gvozdvmozgu\Projects\sqruff> 
```

**Comment by demhadais** [comment]
My apologies - I didn't test the case where it's the only line in the file, in which case the bug doesn't occur. I'm trying to figure out what triggers it in my actual script, I'll reply with what I find shortly.

**Comment by gvozdvmozgu** [comment]
then most likely the error is due to incorrect parsing of the SQL file

**Comment by demhadais** [comment]
Okay, so it seems that
```sql
grant some_role to a_user with admin true;
grant some_role to a_user;
```
gets reformatted to
```sql
grant some_role to a_user with admin true ;
grant some_role to a_user ;
```

**Comment by gvozdvmozgu** [comment]
The part "with admin" breaks the parser.








```yml
file:
- statement:
  - access_statement:
    - keyword: grant
    - whitespace: ' '
    - object_reference:
      - naked_identifier: some_role
    - whitespace: ' '
    - keyword: to
    - whitespace: ' '
    - role_reference:
      - naked_identifier: a_user
- whitespace: ' '
- file:
  - word: with
  - whitespace: ' '
  - word: admin
  - whitespace: ' '
  - word: 'true'
  - semicolon: ;
  - newline: |2+

  - word: grant
  - whitespace: ' '
  - word: some_role
  - whitespace: ' '
  - word: to
  - whitespace: ' '
  - word: a_user
  - semicolon: ;
- end_of_file: ''
```
